export const promos = [
  {
    link: 'https://staging.michaels.com/level-1%2C-2-and-3-back-stapled-and-gallery-wrapped-canvas/ia-canvas',
    img: 'https://staging.michaels.com/on/demandware.static/-/Sites-MichaelsUS-Library/default/dw85efd177/_hp/190721-mik-us-t3-01.png',
    alt: 'Buy Online Pick Up in Store',
    leadIn: 'BUY ONE, GET ONE ',
    offer: 'FREE',
    product: 'ALL Back-Stapled & Gallery Wrapped Canvas',
    brand: 'by Artist’s Loft',
    content: 'Level 1: Academic.',
    content1: 'Level 2: Artist.',
    content2: 'Level 3: Professional.',
    disclaimer: '',
  },
  {
    link: 'https://staging.michaels.com/frame-collections/home-collection/842495143',
    img: 'https://staging.michaels.com/on/demandware.static/-/Sites-MichaelsUS-Library/default/dwf3b6090e/_hp/190721-mik-us-t3-02.png',
    alt: 'Buy Online Pick Up in Store',
    leadIn: 'BUY ONE, GET ONE ',
    offer: 'FREE',
    product: 'Home Wall Frames',
    brand: 'by Studio Decor®',
    content: '',
    content1: '',
    content2: '',
    disclaimer: '',
  },
  {
    link: 'https://staging.michaels.com/albums-and-refills/albums/809188559',
    img: 'https://staging.michaels.com/on/demandware.static/-/Sites-MichaelsUS-Library/default/dwf70012d2/_hp/190721-mik-us-t3-03.png',
    alt: 'Buy Online Pick Up in Store',
    leadIn: 'BUY ONE, GET ONE ',
    offer: 'FREE',
    product: 'Scrapbook & Photo Albums',
    brand: '',
    content: '',
    content1: '',
    content2: '',
    disclaimer: 'Excludes Hot Buy Scrapbook Albums.',
  },
  {
    link: 'https://staging.michaels.com/papercraft/craft-organization/809188640',
    img: 'https://staging.michaels.com/on/demandware.static/-/Sites-MichaelsUS-Library/default/dw099ff5ee/_hp/190721-mik-us-t3-04.png',
    alt: 'Buy Online Pick Up in Store',
    leadIn: '',
    offer: '40% OFF',
    product: 'ALL Craft Storage',
    brand: '',
    content: 'Starting at 2.99',
    content1: '',
    content2: '',
    disclaimer: 'Contents not included.',
  },
  {
    link: 'https://staging.michaels.com/fall/fall-floral/1003275780',
    img: 'https://staging.michaels.com/on/demandware.static/-/Sites-MichaelsUS-Library/default/dw3ffd110f/_hp/190721-mik-us-t3-05.png',
    alt: '',
    leadIn: '',
    offer: '40% OFF',
    product: 'ALL Fall Floral',
    brand: '',
    content: '',
    content1: '',
    content2: '',
    disclaimer: 'Project ideas shown.',
  },
  {
    link: 'https://staging.michaels.com/fall/fall-decor-pieces/1016539344',
    img: 'https://staging.michaels.com/on/demandware.static/-/Sites-MichaelsUS-Library/default/dwc787e111/_hp/190721-mik-us-t3-06.png',
    alt: '',
    leadIn: '',
    offer: '40% OFF',
    product: 'ALL Fall Décor',
    brand: '',
    content: '',
    content1: '',
    content2: '',
    disclaimer: '',
  },
  {
    link: 'https://staging.michaels.com/papercraft/planners/809188563',
    img: 'https://staging.michaels.com/on/demandware.static/-/Sites-MichaelsUS-Library/default/dw5d202bc0/_hp/190721-mik-us-t3-07.png',
    alt: '',
    leadIn: 'OVER 200 NEW STYLES ',
    offer: '30% OFF',
    product: 'Planners & Planner Accessories',
    brand: 'by Recollections™ & The Happy Planner®',
    content: '',
    content1: '',
    content2: '',
    disclaimer: '',
  },
  {
    link: 'https://staging.michaels.com/shop-categories/kids/807060409?prefn1=brand&pmpt=qualifying&prefv1=Crayola',
    img: 'https://staging.michaels.com/on/demandware.static/-/Sites-MichaelsUS-Library/default/dwf7c607c4/_hp/190721-mik-us-t3-08.png',
    alt: '',
    leadIn: 'BUY ONE, GET ONE ',
    offer: '50% OFF',
    product: 'ALL Crayola®',
    brand: '',
    content: '',
    content1: '',
    content2: '',
    disclaimer: '',
  }
];